GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/5e2e4be971a19b64bf242246

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Amazing",
    "subscribedToChannel": "Ava Channel Number 2"
}

###

DELETE http://localhost:3000/subscribers/5e2e4be971a19b64bf242246

###


PATCH http://localhost:3000/subscribers/5e2e54f953c87a67072c039b
Content-Type: application/json

{
    "name": "Ava Callery"
}